name: Slash Focus

on:
  workflow_dispatch:
  push:
    tags:
      - v**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.5.1
    - name: Install dependencies
      run: |
        ls
        npm install -g web-ext
    - name: run build
      run: |
        web-ext build
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: web-ext-artifacts/**.zip
        draft: true
